version: '3'
services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    environment:
      POSTGRES_DB: tester
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    container_name: 'TheShopSite'
    build: ./
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tester
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
