create sequence hibernate_sequence start 1 increment 1;

    create table cart_item (
       id int8 not null,
        amount int4 not null,
        date date,
        product_id int8,
        primary key (id)
    );

    create table feed_back (
       id int8 generated by default as identity,
        date timestamp,
        feed_back_text varchar(1500),
        user_of_shop_id int8,
        primary key (id)
    );

    create table product (
       id int8 generated by default as identity,
        active boolean,
        category varchar(255),
        description varchar(300),
        name varchar(30),
        name_img TEXT,
        price float8 not null check (price>=1),
        primary key (id)
    );

    create table roles (
       user_of_shop_id int8 not null,
        roles varchar(255)
    );

    create table shopping_cart (
       id int8 not null,
        active boolean,
        buyer_name varchar(255),
        complied_order boolean,
        date date,
        location varchar(255),
        token_session varchar(255),
        primary key (id)
    );

    create table shopping_cart_items (
       shopping_cart_id int8 not null,
        items_id int8 not null,
        primary key (shopping_cart_id, items_id)
    );

    create table user_of_shop (
       id int8 generated by default as identity,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    alter table if exists shopping_cart_items 
       add constraint UK_ln84ylb54v72dt5hxftrtas48 unique (items_id);

    alter table if exists user_of_shop 
       add constraint UK_ej4vnjx0unn7xnsk1vv9bxf8n unique (username);

    alter table if exists cart_item 
       add constraint FKjcyd5wv4igqnw413rgxbfu4nv 
       foreign key (product_id) 
       references product;

    alter table if exists feed_back 
       add constraint FKfku2ddgsujiv1k45ia80s4yip 
       foreign key (user_of_shop_id) 
       references user_of_shop;

    alter table if exists roles 
       add constraint FKs59w7g83pjf3h1h0n8ctcb117 
       foreign key (user_of_shop_id) 
       references user_of_shop;

    alter table if exists shopping_cart_items 
       add constraint FKb2m8eb1wsjsqb1ysdkmvnsieq 
       foreign key (items_id) 
       references cart_item;

    alter table if exists shopping_cart_items 
       add constraint FKn4ocuqbcv64d0pvyhv863l1y5 
       foreign key (shopping_cart_id) 
       references shopping_cart;